### PR TITLE
DRAFT: Add optimistic lock for updating projection version

### PR DESCRIPTION
**Pull request by neofelisho**

### CODE REVIEW

**Comment by neofelisho** [comment]
@boatkorachal I still didn't find a good way to test it. Any ideas?

**Comment by boatkorachal** [comment]
ahh.. i know now. it's impossible to test if we use ecto sandbox since we cannot simulate multiple db connections at same time

**Comment by neofelisho** [comment]
> ahh.. i know now. it's impossible to test if we use ecto sandbox since we cannot simulate multiple db connections at same time

Yeah...I thought of a similar thing when I wanna run the raw SQL transaction with multiple steps.

Two TODOs wanna consult your idea:
1. Add `lock_version` column to the `projection_versions` table to let the optimistic lock looks beautiful.
2. Test what we modified (the `two_projectors_test`) without sandbox.

What do you think?

**Comment by boatkorachal** [comment]
1. do you mean you don't like `force_change` right? i've tried with 
```elixir
version
|> Ecto.Changeset.change(updated_at: NaiveDateTime.utc_now())
|> Ecto.Changeset.optimistic_lock(:last_seen_event_number, fn _ -> event_number end)
```
and looks like it worked

2. i've also tried but still confused how postgres transaction isolation works. you can try checkout branch `test-no-ecto-sandbox` and run only that test file `mix test test/projections/two_projectors_test.exs`

**Pull request closed without merging**
